services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Basecom\FixturePlugin\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,spec}'

    _instanceof:
        Basecom\FixturePlugin\Fixture:
            tags: ['basecom.fixture']

    Basecom\FixturePlugin\FixtureLoader:
        arguments:
            - !tagged_iterator basecom.fixture

    Basecom\FixturePlugin\Utils\MediaUtils:
        arguments:
            $mediaRepository: '@media.repository'
            $mediaFolderRepository: '@media_folder.repository'

    Basecom\FixturePlugin\Utils\PaymentMethodUtils:
        arguments:
            $paymentMethodRepository: '@payment_method.repository'
