name: Linting
on: [push]
jobs:
    php-cs-fixer:
        name: PHP-CS-Fixer
        container:
            image: dockware/flex:latest
            options: --user root
        runs-on: ubuntu:18.04

        strategy:
            matrix:
                php-version: [7.4, 8.0, 8.1]

        steps:
            - name: Check out code
              uses: actions/checkout@v3

            #- name: Switch PHP version
            #  run: '(cd /var/www && make switch-php version=${{ matrix.php-version }}'

            - name: Install dependencies
              run: 'cd /var/www/ && composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader'

            - run: './vendor/bin/php-cs-fixer fix --dry-run'